"""empty message

Revision ID: 48d2c5eec25a
Revises: 
Create Date: 2019-05-14 20:52:09.445951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d2c5eec25a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('identity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('workStatus', sa.Integer(), nullable=True),
    sa.Column('departmentID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['department.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('arrangement',
    sa.Column('arragementID', sa.Integer(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=True),
    sa.Column('departmentID', sa.Integer(), nullable=True),
    sa.Column('workDate', sa.Date(), nullable=False),
    sa.Column('beginTime', sa.Time(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('assignment', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['departmentID'], ['department.ID'], ),
    sa.ForeignKeyConstraint(['staffID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('arragementID')
    )
    op.create_table('leave',
    sa.Column('leaveID', sa.Integer(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('leaveReason', sa.String(length=50), nullable=True),
    sa.Column('leaveDate', sa.Date(), nullable=False),
    sa.Column('submitTime', sa.Time(), nullable=False),
    sa.Column('leaveBeginTime', sa.Time(), nullable=False),
    sa.Column('leaveEndTime', sa.Time(), nullable=False),
    sa.Column('isLeavePermitted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staffID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('leaveID')
    )
    op.create_table('overtime',
    sa.Column('overtimeID', sa.Integer(), nullable=False),
    sa.Column('overtimeThreshold', sa.Integer(), nullable=True),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('overtimeBeginTime', sa.Time(), nullable=False),
    sa.Column('overtimeEndTime', sa.Time(), nullable=False),
    sa.Column('overtimeType', sa.Integer(), nullable=False),
    sa.Column('submitTime', sa.Time(), nullable=False),
    sa.Column('isOvertimePermitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staffID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('overtimeID')
    )
    op.create_table('signsheet',
    sa.Column('sheetID', sa.Integer(), nullable=False),
    sa.Column('staffID', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('punchBeginTime', sa.Time(), nullable=True),
    sa.Column('punchEndTime', sa.Time(), nullable=True),
    sa.Column('isLate', sa.Boolean(), nullable=True),
    sa.Column('isEarly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staffID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('sheetID')
    )
    op.create_table('report',
    sa.Column('reportID', sa.Integer(), nullable=False),
    sa.Column('leaveID', sa.Integer(), nullable=False),
    sa.Column('reportTime', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['leaveID'], ['leave.leaveID'], ),
    sa.PrimaryKeyConstraint('reportID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('signsheet')
    op.drop_table('overtime')
    op.drop_table('leave')
    op.drop_table('arrangement')
    op.drop_table('user')
    op.drop_table('department')
    # ### end Alembic commands ###
